language: cpp

os:
  - linux
  - osx

env:
  - VISP_INPUT_IMAGE_PATH=${TRAVIS_BUILD_DIR}
  
compiler:
  - gcc
  - clang

sudo: required
dist: trusty

# branches to build (safelist)
branches:
  only:
  - master
  - test_travis

before_install:
  - cd ${TRAVIS_BUILD_DIR} && { curl -O http://visp-doc.inria.fr/download/dataset/ViSP-images-3.0.0.zip ; cd -; }
  - unzip ${TRAVIS_BUILD_DIR}/ViSP-images-3.0.0.zip -d ${TRAVIS_BUILD_DIR}
  # Get libs for OSX
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew update; fi"
  #- "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew tap homebrew/science; fi"
  #- "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install opencv3; fi"
  - "if [ $TRAVIS_OS_NAME = 'osx' ]; then brew install libxml2 gsl; fi"
  
  # Get libs for Linux
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq cmake libopencv-dev libx11-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq liblapack-dev libgsl0-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libv4l-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libxml2-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libjpeg-dev libpng12-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libswscale-dev libavutil-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libavformat-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq libavcodec-dev libbz2-dev; fi"
  - "if [ $TRAVIS_OS_NAME = 'linux' ]; then sudo apt-get install -qq locate ; fi"

before_script:
  - sudo updatedb 
  - locate libomp.so
  - git clone https://github.com/lagadic/visp.git /tmp/visp
  - mkdir build
  - cd build
  - cmake /tmp/visp -DVISP_CONTRIB_MODULES_PATH=.. -DBUILD_MODULE_visp_ar=OFF -DBUILD_MODULE_visp_blob=OFF -DBUILD_MODULE_visp_detection=OFF -DBUILD_MODULE_visp_klt=OFF -DBUILD_MODULE_visp_mbt=OFF -DBUILD_MODULE_visp_me=OFF -DBUILD_MODULE_visp_tt=OFF -DBUILD_MODULE_visp_tt_mi=OFF -DBUILD_MODULE_visp_vision=OFF -DBUILD_MODULE_visp_visual_features=OFF -DBUILD_MODULE_visp_vs=OFF
  # Show 3rd parties that are detected
  - cat ViSP-third-party.txt

script: 
  - make
  - pwd
  - ls modules/core
  - ./modules/core/testMatrixPseudoInverse
  - ctest -VV

notifications:
  email:
    - Fabien.Spindler@inria.fr
    - marc.pouliquen@inria.fr
  on_success: change
  on_failure: always
